name: build

on:
  push:
    branches: [master]

jobs:
  arm-none-eabi-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --unshallow --tags
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - run: cmake -Bbuild -DARCH="-mcpu=cortex-m4" -DCMAKE_TOOLCHAIN_FILE=CMakeModules/src/toolchains/arm_none_eabi_gcc.cmake
      - run: cmake --build build --target MDU

  x86_64-pc-linux-gnu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --unshallow --tags
      - run: cmake -Bbuild
        env:
          CC:   gcc-13
          CXX:  g++-13
      - run: cmake --build build --target MDU