name: build

on:
  push:
    branches: [master]

jobs:
  arm-none-eabi-gcc:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/arm-none-eabi-gcc.yml@v0.0.1
    with:
      arch: -mcpu=cortex-m4
      target: MDU

  x86_64-linux-gnu-gcc:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/x86_64-linux-gnu-gcc.yml@v0.0.1