name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/ctest.yml@v0.0.3
    with:
      args: -DMDU_TESTS_MASTER_KEY=${{ secrets.MDU_TESTS_MASTER_KEY }}
      target: MDUTests
    secrets: inherit